name: test

on:
  pull_request:
    branches: [ main ]

jobs:
  generate: 
    name: "Generate site"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: "Generate static HTML"
        uses: estebanlm/foliage-action@v1.4.2
        with:
          source: './site'
          target: 'generated'
